### ISSUE TITLE
My name as author

### ISSUE THREAD

**Issue by jgeluk** [lupo49/dokuwiki-plugin-dir#18]
Hi, it's been many years ago since I made that first version of the plugin. I still see my name as the primary and only author, which is very touching but it would be good if anyone else who contributed to this plugin would be mentioned too. Please also remove my email address as I still get emails sometimes of people who want my help and I can't really help them.

Thanks for the great work of keeping this plugin alive :-)

**Comment by lupo49** [comment]
Ok, thanks. I did some changes in the plugin.info.txt.
